# Generated by Django 4.1 on 2022-08-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(default='', max_length=5, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('selected', models.BooleanField(null=True)),
                ('symbol', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('decimals', models.IntegerField(null=True)),
                ('logoURI', models.CharField(max_length=250, null=True)),
                ('chainId', models.IntegerField(null=True)),
                ('pairs', models.CharField(max_length=250, null=True)),
                ('type', models.CharField(max_length=30, null=True)),
                ('asset', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
